### ISSUE TITLE
Import Account csv to Create Book

### ISSUE THREAD

**Issue by flywire** [sdementen/piecash#168]
I offered an approach of [importing account data to create a GnuCash book](https://github.com/Gnucash/gnucash-docs/pull/132) based on the GnuCash Tutorial and Concepts Guide starting at Chapter 5 but it was not adopted. Piecash could do it better because the book and check account could be created, then the chart of accounts built as they are encountered. 

I think it would be a worthwhile example program to include in the documentation as `Import transactions from a CSV file to create a book` before `Export transactions to a CSV file`.

The most important part is shown below. The transactions from the check bank statement should have an `Opening balance` of $1,000.00 on 1 Mar 06 coded as from `Equity:Opening Balance` and `Entity` becomes `Description`.

> **Importing a Bank Statement**
> 
> The following file is typical of a checkbook statement. Note in this instance fields are separated by tabs instead of commas.
> 
> ~~~
> Date	Number	Description	Amount	Balance
> 05/03/06	101	GG25j1546 Groceries    wtf 15:57 061124	-45.21	413.05
> 06/03/06		Transfer to J&J Doe Savings Acc 5765-8397 589654259587	100.00	513.05
> 14/03/06		Direct Credit Salary from Employers R Us	670.00	1,183.05
> 28/03/06		Mmvoin515b  Internet Company bg??	-20.00	1,163.05
> 28/03/06	102	Light Company Big City Branch   9g8k863	-78.00	1,085.05
> 28/03/06	103	Phone Company Name    Autodebit 595642583	-45.00	1,040.05
> 28/03/06	104	Internet Transfer         April Rent 5 Short Road	-350.00	690.05
> ~~~
> 
> The good things about bank data are the transaction dates, numbers (if used) and amounts. A lot more data is required in a cashbook which is normally got by decoding the description to determine the payee and account, and the class and memo if they are used. This decoding can be slow and error-prone so a preprocessor can make the process more accurate and efficient.
> 
> This guide assumes a preprocessor is used to enrich the bank statement before it is imported. You can use a spreadsheet, python program, or search for another program to process the files. Save the following data to _CheckStatementEnriched.csv_ which has Account and Payee fields added:
> 
> ~~~
> Date,Number,Memo,Amount,Balance,Account,Entity
> 05/03/06,101,GG25j1546 Groceries    wtf 15:57 061124,-45.21,413.05,Expenses:Groceries,Big Food
> 06/03/06,,Transfer to J&J Doe Savings Acc 5765-8397 589654259587,100,513.05,Assets:Savings,[Savings]
> 14/03/06,,Direct Credit Salary from Employers R Us,670,1183.05,Income:Salary,Employers R Us
> 28/03/06,,Mmvoin515b  Internet Company bg??,-20,1163.05,Expenses:Internet,FastFibre
> 28/03/06,102,Light Company Big City Branch   9g8k863,-78,185.05,Expenses:Electricity,Light Company
> 28/03/06,103,Phone Company Name    Autodebit 595642583,-45,140.05,Expenses:Phone,Phone Company Name
> 28/03/06,104,April Rent        5 Short Road,-350,690.05,Expenses:Rent,HighTower
> ~~~

**Comment by sdementen** [comment]
Can I provide you help you in some way?

**Comment by flywire** [comment]
Give me some time. I assume you are receptive to including the example in the docs.

I've started to run the docs examples, It's not immediately obvious how the `piecash/examples/` relate to the docs (file download link would be nice). After `$ pip install piecash[pandas,qif,yahoo]` I started with [Create a book with some accounts and add a transaction](https://piecash.readthedocs.io/en/master/tutorial/examples.html#create-a-book-with-some-accounts-and-add-a-transaction) generating a page full of errors. iirc `simple_move_split.py` `pytest`?? was not installed so I installed it and the other examples seem to be running now (although it could have just been an issue with the first one). Maybe some are using developer libraries.

**Comment by flywire** [comment]
Let start:

```python
FILE = "../gnucash_books/simple_csv_book_creation.gnucash"
# open file rw if it exists else create it and open it rw
book = open(FILE,"w+")
```

So I opened the file not the book. How's that api work? (I've worked through the examples.) Pretty well the same process for each account in each transaction.

**Comment by sdementen** [comment]
I am not sure if there is any implicit question in your last post... but your code is strange... your opening the file in plain python, not using piecash.
Anyway, if you want to learn/use piecash, I would suggest to start from an example (e.g. https://piecash.readthedocs.io/en/master/tutorial/index_existing.html#access-to-objects) and adapt it so it reads your gnucash file.

**Comment by flywire** [comment]
Yes, I'm trying to tidy up:

```python
FILE = "../gnucash_books/simple_csv_book_creation.gnucash"

# open book file
try:
    mybook = open_book(FILE)
except GnucashException as backend_exception:
    # print("OK", backend_exception)
    # create book file
    with create_book(FILE) as mybook:
        pass
```

All the examples start with no file or an existing file, none allow for either.

After that I used `with mybook:`

**Comment by sdementen** [comment]
starting from no book (and so creating an empty book) vs starting from an initialised book (with the accounts) is quite a different scenario for the user (technically, you can put some magic to make them similar but that's not the issue) ==> the example are focused on typical user use cases.

for your code, I would rather be more explicit with 
```python
FILE = "../gnucash_books/simple_csv_book_creation.gnucash"

if os.path.exists(FILE):
    # open book file
    mybook = open_book(FILE)
else::
    # create book file
    mybook = create_book(FILE)
```
to avoid catching exception raised by open_book that are not due to the inexistence of the file.

**Comment by flywire** [comment]
Wondering how to check account existance:

```python
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from piecash import open_book, create_book, GnucashException, Account
>>> FILE = "../gnucash_books/simple_csv_book_creation.gnucash"
>>> mybook = create_book(FILE, overwrite=True)
>>> print("Account: ", mybook.accounts(fullname="Assets:Checking"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\piecash\_common.py", line 180, in __call__
    raise KeyError(
KeyError: "Could not find object with {'fullname': 'Assets:Checking'} in []"
>>>>
```

Next I'll look at stepping through account tree checking if account exists then create if not.

**Comment by sdementen** [comment]
you can use this approach (with the KeyError).
if needed, you can add an helper like
```python
def get_or_none(collection, **kwargs):
    try:
        return collection(**kwargs)
    except KeyError:
        return None
```
or a more specific function that would create the account recursively if it does not exist (not tested but you get the idea)
```python
def get_or_create_account(book, fullname, type):
    try:
        return book.accounts(fullname=fullname)
    except KeyError:
        parent_name, child_name = fullname.resplit(":",1)
        return Account(name=child_name,
              type=type,
              parent=get_or_create_account(book, parent_name, type),
              commodity=EUR,
              placeholder=False,)
```

**Comment by flywire** [comment]
I can't figure out how to create account with `parent_name` string (eg [Creating a new Account](https://piecash.readthedocs.io/en/master/tutorial/index_new.html#creating-a-new-account) uses `acc`).

btw, seems subacc defaults to `placeholder=True` in that example too.

**Comment by sdementen** [comment]
You cannot. You need to get the parent account object before creating the child account.

**Comment by flywire** [comment]
Tried to make consistent with Piecash documentation.

Works. Any tidy up contributions welcome:
1. requires first level accounts to match [account type](https://www.gnucash.org/docs/v2.6/C/gnucash-help/acct-types.html),
1. will import (duplicate) transaction every time it is run,
1. could use `*argv`, `**kwargs` and `default_currency`,
1. `post_date=today.date(),                  # fix this`

Will I do a PR?

**simple_csv_book_creation.py**
```python
from piecash import open_book, create_book, GnucashException, Account
import os
import tempfile

def get_or_create_account(book, fullname, type):
    # get_or_create_accounts
    acc_tree = ""
    for name in fullname.split(":"):
        if acc_tree:
            acc_tree += ":"+name
        else:
            acc_tree = name
            acc = book.root_account
        try:
            acc = book.accounts(fullname=acc_tree)
            # print("> Found: ", acc_tree)
        except KeyError:
            # print("> Create: ",  name)
            acc=Account(name=name,
                  type=type,
                  parent=acc,
                  commodity=EUR,
                  placeholder=False,)
            book.flush()
    return(acc)

def print_coa():
    # basic account listing
    print()
    for account in book.accounts:
        print(account)
    return()

def basic_coa():
    # get_or_create_accounts
    get_or_create_account(book, fullname="Asset", type="ASSET")
    get_or_create_account(book, fullname="Asset:Cheque", type="BANK")
    get_or_create_account(book, fullname="Asset:Saving", type="BANK")
    get_or_create_account(book, fullname="Expense", type="EXPENSE")
    get_or_create_account(book, fullname="Income", type="INCOME")
    return()

def test_accounts():
    fullname="Assets"
    type="ASSET"
    get_or_create_account(book, fullname, type)
    
    fullname="Assets:Cheque"
    type="BANK"
    get_or_create_account(book, fullname, type)
    
    fullname="Expenses:Expenses:Holiday:Acc"
    type="EXPENSE"
    get_or_create_account(book, fullname, type)
    
    fullname="Expenses:Fuel"
    get_or_create_account(book, fullname, type)
    
    fullname="Expenses:Expenses:Holiday:Travel"
    get_or_create_account(book, fullname, type)

    return()


FILE = "../gnucash_books/simple_csv_book_creation.gnucash"

if os.path.exists(FILE):
    print("Found: ", FILE)
    # open book file
    book = open_book(FILE, readonly=False, open_if_lock=True, do_backup=False)
else:
    # create book file
    book = create_book(FILE, overwrite=True, currency="EUR")
    print("Created: ", FILE)

# retrieve the default currency
EUR = book.commodities.get(mnemonic="EUR")

# test_accounts()
basic_coa()
# print_coa()

import csv
from piecash import open_book, Transaction, Split
from datetime import datetime
from decimal import Decimal

today = datetime.now()
import_account = get_or_create_account(book, fullname="Asset:Cheque", type="BANK")

with open('import.csv', 'r') as file:
    csv_file = csv.DictReader(file)
    for row in csv_file:

        # reformat data as required
        transfer_account = get_or_create_account(book, fullname=row['Account'], type=row['Account'].split(':')[0].upper())
        amount = Decimal(row['Amount'])
        dt_obj=datetime.strptime(row['Date'], '%d/%m/%y')

        # create the transaction with its two splits
        Transaction(
            post_date=today.date(),                  # fix this
            enter_date=today,
            currency=EUR,
            description=row['Entity'],
            splits=[
                Split(account=import_account, value=amount, memo=row['Memo']),
                Split(account=transfer_account, value=-amount, memo=row['Memo']),
            ],
        )
    # save the book
    book.save()
```
![](https://www.gnucash.org/docs/v4/C/gnucash-guide/figures/cbook_checkexamp.png)

Statement data has been enhanced.

**import.csv**
```
"Date","Number","Memo","Amount","Balance","Account","Entity"
01/03/06,,"Opening Balance",1000,1000,"Equity:Opening Balance","Opening Balance"
05/03/06,101,"GG25j1546 Groceries    wtf 15:57 061124",-45.21,954.79,"Expense:Groceries","Grocery Store"
05/03/06,,"EFTOS 5632185",-75,879.79,"Expense:Groceries","HomeTown Grocery"
06/03/06,,"Transfer to J&J Doe Savings Acc 5765-8397 589654259587",100,979.79,"Asset:Saving","Saving"
06/03/06,106,"EFTOS 98416",-100,879.79,"Expense:Hardware","ABC Hardware"
14/03/06,,"Direct Credit Salary from Employers R Us",670,1549.79,"Income:Salary","Employers R Us"
24/03/06,,"Transfer to J&J Doe Savings Acc 5765-8397 589654259587",500,2049.79,"Asset:Saving","Transfer Money"
28/03/06,,"Mmvoin515b  Internet Company bg??",-20,2029.79,"Expense:Internet","FastFibre"
28/03/06,102,"Light Company Big City Branch   9g8k863",-78,1951.79,"Expense:Electricity","Light Company"
28/03/06,103,"Phone Company Name    Autodebit 595642583",-45,1906.79,"Expense:Phone","Phone Company Name"
28/03/06,104,"April Rent        5 Short Road",-350,1556.79,"Expense:Rent","HighTower"
"28/04/06",105,"May Rent        5 Short Road",-350,1206.79,"Expense:Rent","HighTower"
```
