### ISSUE TITLE
Code in Documentation Doesn't Run

### ISSUE THREAD

**Issue by flywire** [sdementen/piecash#169]
[Quickstart](https://piecash.readthedocs.io/en/master/doc/doc.html#quickstart)

> book = piecash.open_book("test.gnucash", readonly=True)

 - Appears intended to be executable but no file provided.

---

> Or in python
>
> `book = open_book(gnucash_books + "simple_sample.gnucash", open_if_lock=True)`

Running in `\piecash-master\examples\`
```python
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> book = open_book(gnucash_books + "simple_sample.gnucash", open_if_lock=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'open_book' is not defined
>>>
>>> import piecash
>>> book = open_book(gnucash_books + "simple_sample.gnucash", open_if_lock=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'open_book' is not defined
>>> book = piecash.open_book(gnucash_books + "simple_sample.gnucash", open_if_lock=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'gnucash_books' is not defined
>>> gnucash_books=""
>>> book = piecash.open_book(gnucash_books + "simple_sample.gnucash", open_if_lock=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\piecash\core\session.py", line 409, in open_book
    raise GnucashException(
piecash._common.GnucashException: Database 'sqlite:///simple_sample.gnucash' does not exist (please use create_book to create GnuCash books from scratch). If you want to bypass this existence check, use the argument check_exists=False.
>>>
```

**Comment by flywire** [comment]
Any examples with `(gnucash_books + "` probably should have the following declaration on the preceeding line so they run from `./examples/`:
```python
gnucash_books = "../gnucash_books/"
```

Adding to each page:
```rst
.. note::

   Examples can be run from `./examples/` folder
```

**Comment by flywire** [comment]
Documentation problem needs fixing - `gnucash_books` not declared:

Search "(gnucash_books" (8 hits in 7 files)
 piecash\docs\source\doc\doc.rst (1 hit)
Line 205:     book = open_book(gnucash_books + "simple_sample.gnucash", open_if_lock=True)
 \piecash\docs\source\tutorial\existing_objects\transaction.rst (1 hit)
Line 8:     book = open_book(gnucash_books + "book_schtx.gnucash", open_if_lock=True)
 \piecash\docs\source\tutorial\existing_objects\account.rst (1 hit)
Line 8:     book = open_book(gnucash_books + "simple_sample.gnucash", open_if_lock=True)
 \piecash\docs\source\tutorial\existing_objects\invoices.rst (1 hit)
Line 8:     book = open_book(gnucash_books + "invoices.gnucash", open_if_lock=True)
 \piecash\docs\source\tutorial\existing_objects\commodity.rst (1 hit)
Line 8:     book = open_book(gnucash_books + "book_prices.gnucash", open_if_lock=True)
 \piecash\docs\source\tutorial\existing_objects\open_book.rst (2 hits)
Line 44:         In [1]: book = open_book(gnucash_books + "default_book.gnucash")
Line 75:         book = open_book(gnucash_books + "default_book.gnucash")
 \piecash\docs\source\tutorial\existing_objects\others.rst (1 hit)
Line 8:     book = open_book(gnucash_books + "invoices.gnucash", open_if_lock=True)

---

Typical path in examples:

GNUCASH_BOOK = "../gnucash_books/simple_sample.gnucash"

---
---

Probably should add to each page:
```rst
.. note::

   Examples can be run from `./examples/` folder
```
