### ISSUE TITLE
MySQLdb module missing

### ISSUE THREAD

**Issue by ifuchs** [sdementen/piecash#195]
I did an install of piecash with:

`pip install -U piecash[pandas,mysql] `

and now if I try to do an open_book with a mysql uri, I am getting 

"ModuleNotFoundError: No module named 'MySQLdb'"

I was pretty sur ethat my sqlalchemy had MySQL support. What am I missing?

**Comment by sdementen** [comment]
I see "bin/sh: mysql_config: command not found" in your log. Is MySQL installed on your system?
Piecash only installs the pyrhon->MySQL interface but you should already have MySQL installed.

**Comment by ifuchs** [comment]
That's a good question. I tried to install mysqlclient but it failed:

`pip install mysqlclient
Collecting mysqlclient
  Using cached mysqlclient-2.1.0.tar.gz (87 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  Ã python setup.py egg_info did not run successfully.
  â exit code: 1
  â°â> [16 lines of output]
      /bin/sh: mysql_config: command not found
      /bin/sh: mariadb_config: command not found
      /bin/sh: mysql_config: command not found
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/y2/38gkkc0s7d52_mr_s6zfj7m80000gq/T/pip-install-jhyhz4q5/mysqlclient_7d815c9d48da443fb56a51023ad822bf/setup.py", line 15, in <module>
          metadata, options = get_config()
        File "/private/var/folders/y2/38gkkc0s7d52_mr_s6zfj7m80000gq/T/pip-install-jhyhz4q5/mysqlclient_7d815c9d48da443fb56a51023ad822bf/setup_posix.py", line 70, in get_config
          libs = mysql_config("libs")
        File "/private/var/folders/y2/38gkkc0s7d52_mr_s6zfj7m80000gq/T/pip-install-jhyhz4q5/mysqlclient_7d815c9d48da443fb56a51023ad822bf/setup_posix.py", line 31, in mysql_config
          raise OSError("{} not found".format(_mysql_config_path))
      OSError: mysql_config not found
      mysql_config --version
      mariadb_config --version
      mysql_config --libs
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Ã Encountered error while generating package metadata.
â°â> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by ifuchs** [comment]
pip install mysqlclient fails but conda install mysqlclient seems to have worked.

**Comment by sdementen** [comment]
I think you need to install mysql from https://www.mysql.com/downloads/
(which is unrelated to python and is a database server like postgresql &
co).

probably conda has detected you needed it and so installed it for you
(conda can also install non python dependencies)
