### ISSUE TITLE
failure on create transaction with postgres backend

### ISSUE THREAD

**Issue by jaredchurch** [sdementen/piecash#242]
transaction guid appears to not be created.
- I get the same error in python 3.8 & 3.12
- Running under linux

This is script that I'm running is:
```
import piecash
import urllib.parse


user=urllib.parse.quote('user')
password=urllib.parse.quote('password')
url='postgres:5432/gnucash2'
uri_conn="postgresql://"+ user +":"+ password +"@"+ url

# book = piecash.open_book(uri_conn=uri_conn, readonly=True)
book = piecash.open_book(uri_conn=uri_conn, readonly=False, do_backup=False)



# Get the default currency (e.g., EUR)
currency = book.default_currency

# Create two accounts
account1 = book.accounts[-2] #piecash.Account(name="Account 1", type="ASSET", parent=book.root_account, commodity=currency)
account2 = book.accounts[-1] #piecash.Account(name="Account 2", type="ASSET", parent=book.root_account, commodity=currency)

# Create a transaction
transaction = piecash.Transaction(
    currency=currency,
    description="Sample transaction",
    splits=[
        piecash.Split(account=account1, value=-100),
        piecash.Split(account=account2, value=100)
    ]
)
book.transactions.append(transaction)

book.flush()
```

The error on book.flush() is:

```
/home/codespace/.local/lib/python3.8/site-packages/piecash/core/book.py:305: SAWarning: Object of type <Transaction> not in session, add operation along 'Split.transaction' won't proceed
  self.session.flush()
Traceback (most recent call last):
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/codespace/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.NotNullViolation: null value in column "tx_guid" of relation "splits" violates not-null constraint
DETAIL:  Failing row contains (7546f879f9c94b68b2ff13a5dcc9161d, null, 231a384fbc9b44818a867e742ca6e935, , , n, null, -100, 1, -100, 1, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "investigate.py", line 33, in <module>
    book.flush()
  File "/home/codespace/.local/lib/python3.8/site-packages/piecash/core/book.py", line 305, in flush
    self.session.flush()
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1156, in _emit_insert_statements
    c = connection._execute_20(
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/codespace/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/codespace/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "tx_guid" of relation "splits" violates not-null constraint
DETAIL:  Failing row contains (7546f879f9c94b68b2ff13a5dcc9161d, null, 231a384fbc9b44818a867e742ca6e935, , , n, null, -100, 1, -100, 1, null).

[SQL: INSERT INTO splits (guid, tx_guid, account_guid, memo, action, reconcile_state, reconcile_date, value_num, value_denom, quantity_num, quantity_denom, lot_guid) VALUES (%(guid)s, %(tx_guid)s, %(account_guid)s, %(memo)s, %(action)s, %(reconcile_state)s, %(reconcile_date)s, %(value_num)s, %(value_denom)s, %(quantity_num)s, %(quantity_denom)s, %(lot_guid)s)]
[parameters: ({'guid': '7546f879f9c94b68b2ff13a5dcc9161d', 'tx_guid': None, 'account_guid': '231a384fbc9b44818a867e742ca6e935', 'memo': '', 'action': '', 'reconcile_state': 'n', 'reconcile_date': None, 'value_num': -100, 'value_denom': 1, 'quantity_num': -100, 'quantity_denom': 1, 'lot_guid': None}, {'guid': '63b43b0d55fc4cac8518684ec51f86b7', 'tx_guid': None, 'account_guid': 'afea20737d644699bd8f68a5257bd3b7', 'memo': '', 'action': '', 'reconcile_state': 'n', 'reconcile_date': None, 'value_num': 100, 'value_denom': 1, 'quantity_num': 100, 'quantity_denom': 1, 'lot_guid': None})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Comment by jaredchurch** [comment]
To add, I did an attempt of the same using in memory sqlite and it succeeded.

```
import piecash

book=piecash.create_book(currency='NZD')
c1 = book.default_currency
a1 = piecash.Account("Acc 1", "ASSET", c1, parent=book.root_account)
a2 = piecash.Account("Acc 2", "ASSET", c1, parent=book.root_account)

tr = piecash.Transaction(currency=c1,
    description="transfer",
    splits=[
        piecash.Split(account=a1, value=-100),
        piecash.Split(account=a2, value=100)
    ])


book.flush()

```

**Comment by jaredchurch** [comment]
scratch that - I found the error (always just after raising it!)

book.default_currency was empty, fixing this resolved the issue.
