### ISSUE TITLE
Column 'tx_guid' cannot be null

### ISSUE THREAD

**Issue by jchonig** [sdementen/piecash#48]
I'm attempting to get piecash to record transactions to my mysql backed GnuCash book and am running into this error: 

> sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.OperationalError) (1048, "Column 'tx_guid' cannot be null") [SQL: u'INSERT INTO splits (guid, tx_guid, account_guid, memo, action, reconcile_state, reconcile_date, value_num, value_denom, quantity_num, quantity_denom, lot_guid) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: ('5d580b426f9142f4ac63183410f1bbd9', None, '01fcbb6b2aece5c7ba17d737a9fa5f02', '', '', 'n', None, -58600, 100, -58600, 100, None)] 

My code that creates a transaction looks like this: 

```
            splits = [] 
            splits.append(piecash.Split(account=providerp, 
                                        value=-trans.total)) 
            if ucr: 
                splits.append(piecash.Split(account=providerp, 
                                            memo="UCR", 
                                            value=ucr)) 
            splits.append(piecash.Split(account=providerp, 
                                        memo=trans.insurer.name + " Paid", 
                                        value=trans.paid)) 
            splits.append(piecash.Split(account=insurerp, 
                                        value=trans.paid)) 

            gtrans = piecash.Transaction(currency=book.default_currency, 
                                         post_date=trans.service_date, 
                                         enter_date=datetime.datetime.now(), 
                                         num=trans.number, 
                                         description=trans.description, 
                                         splits=splits) 

```
As far as I can see I am following the examples in the docs. 

I'm using GnuCash 2.6.17. 

Any help would be appreciated. 

Thanks. 

Jeff

**Comment by sdementen** [comment]
Could you tell at which line the exception raises (or full traceback) ? 
Coud you also save you book in sqlite and test the same script on the sqlite saved book ?
I can't reproduce the bug on a sqlite example with the following script:
```
import os
from datetime import datetime

import piecash

from piecash import create_book, Account, open_book
from piecash.core.factories import create_currency_from_ISO

filename = os.path.abspath('test.blob')
if os.path.exists(filename):
    os.remove(filename)

with create_book(filename) as book:
    providerp = Account(parent=book.root_account,
                        name="wow",
                        type="ASSET",
                        commodity=create_currency_from_ISO("CAD"))
    insurerp = Account(parent=book.root_account,
                       name="waw",
                       type="ASSET",
                       commodity=create_currency_from_ISO("CAD"))

    ucr = 0


    class Trans:
        pass


    trans = Trans()
    trans.total = 100
    trans.paid = 50
    trans.name = "foo"
    trans.number = 50
    trans.description = "fooeofez"
    trans.service_date = datetime.now()

    splits = []
    splits.append(piecash.Split(account=providerp,
                                value=-trans.total))
    if ucr:
        splits.append(piecash.Split(account=providerp,
                                    memo="UCR",
                                    value=ucr))
    splits.append(piecash.Split(account=providerp,
                                memo=trans.name + " Paid",
                                value=trans.paid))
    splits.append(piecash.Split(account=insurerp,
                                value=trans.paid))

    gtrans = piecash.Transaction(currency=book.default_currency,
                                 post_date=trans.service_date,
                                 enter_date=datetime.now(),
                                 num=trans.number,
                                 description=trans.description,
                                 splits=splits)

    book.save()

```

**Comment by jchonig** [comment]
Here's the traceback:

> Traceback (most recent call last):
  File "/vol/records/RecordKeeper/recordkeeper.py", line 310, in <module>
    main()
  File "/vol/records/RecordKeeper/recordkeeper.py", line 297, in main
    insurer.record(gnucash)
  File "/vol/records/RecordKeeper/aetna.py", line 948, in record
    gnucash.add(transactions)
  File "/vol/records/RecordKeeper/gnucash_if.py", line 325, in add
    gtrans = piecash.Transaction(currency=book.default_currency,
  File "/usr/local/lib/python2.7/dist-packages/piecash/core/book.py", line 137, in default_currency
    return self["default-currency"].value
  File "/usr/local/lib/python2.7/dist-packages/piecash/kvp.py", line 83, in __getitem__
    for sl in self.slots:
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 557, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 635, in _emit_lazyload
    result = q.all()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2854, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1422, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1412, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2192, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2276, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 384, in execute
    n.execute_aggregate(self, set_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 481, in execute_aggregate
    self.execute(uow)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.OperationalError) (1048, "Column 'tx_guid' cannot be null") [SQL: u'INSERT INTO splits (guid, tx_guid, account_guid, memo, action, reconcile_state, reconcile_date, value_num, value_denom, quantity_num, quantity_denom, lot_guid) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: ('8b6dfc1edd744dccbd3002c9363e3eb3', None, '01fcbb6b2aece5c7ba17d737a9fa5f02', '', '', 'n', None, -58600, 100, -58600, 100, None)]

**Comment by sdementen** [comment]
ok, can you get first the book.default_currency and then use it in your transaction ?
like
```
curr = book.default_currency
splits = [] 
splits.append(piecash.Split(account=providerp, 
                                        value=-trans.total)) 
...
gtrans = piecash.Transaction(currency=curr, 
                                         post_date=trans.service_date, 
                                         enter_date=datetime.datetime.now(), 
                                         num=trans.number, 
                                         description=trans.description, 
                                         splits=splits) 
```

**Comment by jchonig** [comment]
That got me past this error!

Now to continue debugging my code (I'm not passing the date in the proper format).

Thanks.

Jeff
