### ISSUE TITLE
update price got error

### ISSUE THREAD

**Issue by gorf** [sdementen/piecash#97]
my source code is at :  https://paste.pound-python.org/show/DqQRN04pPRAcVCqDGrrg/
I can use it to update price when there is no price history at today. or there will be error.
https://paste.pound-python.org/show/4tBCiLP219wiDSFZzuTj/
I cannot solve it.
I'll be pleased for somebody's help.

**Comment by sdementen** [comment]
Could you post the error message you get?

**Comment by gorf** [comment]
Thank you. The second link is the error message. I paste it here also.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 2884, in one
    ret = self.one_or_none()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 2863, in one_or_none
    "Multiple rows were found for one_or_none()")
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lq/.local/lib64/python3.6/site-packages/piecash-0.18.0-py3.6.egg/piecash/core/commodity.py", line 97, in validate
    date=self.date).one()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 2887, in one
    "Multiple rows were found for one()")
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./get_online_stock_prices.py", line 157, in <module>
    acquire_online_prices(DATABASE_PATH)
  File "./get_online_stock_prices.py", line 144, in acquire_online_prices
    book.save()
  File "/home/lq/.local/lib64/python3.6/site-packages/piecash-0.18.0-py3.6.egg/piecash/core/book.py", line 270, in save
    self.session.commit()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 436, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/event/attr.py", line 246, in __call__
    fn(*args, **kw)
  File "/home/lq/.local/lib64/python3.6/site-packages/piecash-0.18.0-py3.6.egg/piecash/core/book.py", line 214, in validate_book
    tx.validate()
  File "/home/lq/.local/lib64/python3.6/site-packages/piecash-0.18.0-py3.6.egg/piecash/core/commodity.py", line 99, in validate
    raise ValueError("{} already exists in this book".format(self))
ValueError: Price<2018-09-07 : 6 CNY/600016.SS> already exists in this book

**Comment by sebastiendementen** [comment]
Here is an example on how to modify an existing price (as indeed you cannot have two prices for the same day and commodity):
```python
from datetime import date

import piecash
from piecash import Commodity, Price

# create a new book
with piecash.create_book() as book:
    # create a commodity/stock
    cdty = Commodity("NYSE", "WOCA", "wonder cola", book=book)

    # create two quotes/prices
    p = Price(cdty, book.default_currency, date(2018, 9, 6), "3.44")
    p = Price(cdty, book.default_currency, date(2018, 9, 7), "3.52")

    # save the book
    book.save()

    # create a second price for the second day
    p = Price(cdty, book.default_currency, date(2018, 9, 7), "3.45")

    # save the book ==> raise exception when validating the book as duplicate price
    try:
        book.validate()
    except ValueError:
        print("You cannot have two price for same commodity and day")

    # cancel last operations
    book.cancel()

    # to change a price, retrieve it first and then modify it
    # retrieve price for given day
    price = book.prices(commodity=cdty, date=date(2018, 9, 7))
    print(price)
    price.value = "3.45"

    book.save()
    
    # check prices have been modified correctly
    print(book.prices)

    # you can also use a helper that will either add or modify a price
    def add_or_update_price(cdty, curr, day, value):
        try:
            price = book.prices(commodity=cdty, date=day)  # raise a KeyError if Price does not exist
            print("--> modifying existing price ", price)
            price.value = value
        except KeyError:
            price = Price(cdty, curr, day, value)
            print("--> adding new price ", price)


    add_or_update_price(cdty, book.default_currency, date(2018, 9, 9), 5)
    book.save()


    add_or_update_price(cdty, book.default_currency, date(2018, 9, 9), 6)
    book.save()

```

**Comment by gorf** [comment]
Thank you very much. I'll review it carefully.

**Comment by sdementen** [comment]
Ok, do not hesitate to close the issue if you think it can be closed once you have tested the solution

**Comment by gorf** [comment]
Solved it with this method. Wonderful. Thanks again.
